# Generated by Django 6.0.3 on 2026-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
